# Generated by Django 5.1.1 on 2025-08-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('about_you', models.TextField(blank=True)),
            ],
        ),
    ]
